### ISSUE TITLE
Tweak Attenuation 

### ISSUE THREAD

**Issue by MaximeM** [DolbyIO/comms-sdk-web-extensions#10]
Hello,

Do you know if the attenuation can be tweaked:

I'm creating my spatial environment like so:

setSpatialEnvironment(1);

```
const setSpatialEnvironment = async (axis_scale) => {
    const scale = { x: axis_scale, y: axis_scale, z: axis_scale }
    const forward = { x: 0, y: -1, z: 0 };
    const up = { x: 0, y: 0, z: 1 };
    const right = { x: 1, y: 0, z: 0 };
    VoxeetSDKExt.privateZones.setSpatialEnvironment(scale, forward, up, right);

    await CreateZone(axis_scale);
};

```
Zone around participant:
```
const CreateZone = async (axis_scale) => {
     zone = {
        origin: {
            x: 0,
            y: 0,
            z: 0,
        },
        dimension: {
            x: 20,
            y: 20,
            z: 20 ,
        },
        scale: {
            x: axis_scale,
            y: axis_scale,
            z: axis_scale
        },
    };
    // Create a new private zone with the rules set above in the zone object
    zoneId = await VoxeetSDKExt.privateZones.createZone(zone);
}
```

My problem is that attenuation is way to intense:

If participant is in (0,0,0)  and speaker in (4,0,0) the speaker volume is really low.

Do you know what could be done to have control on attenuation ?

**Comment by FabienLavocat** [comment]
Hi @MaximeM,
With the scale set to 1, having the position (0, 0, 0) and (4, 0, 0) will be a big gap so the attenuation will be important.
What I usually do is to set the hearing zone as the scale, for example if you have a cube (or square) around you where you want someone to hear you, set the size of that cube as the scale. Here is an example: https://github.com/dolbyio-samples/dolbyio-spatial-audio-demo-web/blob/main/src/scripts/script.js#L140-L152

**Comment by FabienLavocat** [comment]
@MaximeM check out this guide on how to configure the scale based on the dimensions of your window: https://docs.dolby.io/communications-apis/docs/guides-integrating-individual-spatial-audio#configure-the-spatial-environment-scale

Where did you find those settings? Our SDK does not have anything like that:
```js
audioSettings: { chromeCutOffVolume: 0.06, distanceModel: "linear", refDistance: 1, maxDistance: 15, rollOffFactor: 1, gain: 1 },

this.stereoPanner.coneOuterAngle = 360;
this.stereoPanner.coneInnerAngle = 360;
```

To run your tests, I highly recommend for you to use the [demo()](https://github.com/dolbyio-samples/dolbyio-spatial-audio-demo-web/blob/main/src/scripts/script.js#L294) function. But also use the `individual` scene so you can move the other participants (bots) easily.

**Comment by FabienLavocat** [comment]
I'll close this ticket for now, if you have further questions, don't hesitate to reach out.
